### ISSUE TITLE
Give PVC priority?

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/application-templates#154]
Please see https://github.com/openshift/origin/issues/8999 for the rationale.

In short: Should we update all templates that use PVC to define them as the first item in JSON files?

**Comment by josefkarasek** [comment]
I don't think this is the case. The referenced issue is concerned about `pods`, but in templates the object consuming PVC is `Deployment Config`. A new deployment is started only if all prerequisites have been met (all necessary Image Streams, Service Accounts and Persistent Volume Claims exist). If not, the deployment is suspended in state of `pending`.
