### ISSUE TITLE
I am unable to deploy wars on openshift 3.0 with tomcat / jboss images

### ISSUE THREAD

**Issue by Arun129** [jboss-openshift/application-templates#206]
Hi All,
I have tried deploying many sample applications on openshfit online v3.0 using default tomcat and jboss images. I am not getting any errors logs during build as well as on deployments. But I am getting a complete blank page as a result of the deployment. I am using git repositories for source code management. Same sample applications are getting deployed successfully in AWS Elastic Beanstalk. 

I hope deployments on openshift 3.0 is success but why am not getting the final web page???

Any suggestions/ideas please ???

**Comment by josefkarasek** [comment]
Can you check the logs of your application?
```oc logs <pod_name>```
Look for `ROOT.war`.

Make sure your pom.xml uses the openshift plugin like [here](https://github.com/jboss-developer/jboss-eap-quickstarts/blob/7.1.x-develop/helloworld-rs/pom.xml#L178-L200). Only root wars are deployed as `/` of your app context.

**Comment by spolti** [comment]
You can check our application templates and examples:
https://github.com/jboss-openshift/application-templates
https://github.com/jboss-openshift/openshift-examples

**Comment by Arun129** [comment]
When I am using jboss images...I have used the sample repository which was provided by openshift during the project creation. https://github.com/jboss-developer/jboss-eap-quickstarts.git 

While using this, am getting sample webpage. But when I am using tomcat with some sample hello world applications, I am not getting the expected webpage.

Is it possible to use oc for the applications hosted in openshift online?? Please confirm @josefkarasek

**Comment by josefkarasek** [comment]
Yes, click the question mark icon in the right upper corner -> command line tools

**Comment by Arun129** [comment]
[tomcatlogs.txt](https://github.com/jboss-openshift/application-templates/files/585961/tomcatlogs.txt)


Please find the attachment of logs...are you able to find anything fishy??

**Comment by spolti** [comment]
I can't see your application getting deployed, can you please the app sources that you are trying to deploy?
Plus, when you create your new pod, are you able see the s2i build process?

**Comment by rcernich** [comment]
There is a difference between EAP and Tomcat.  EAP provides a full JavaEE platform, whereas Tomcat is only a web server.  Because of this, it's possible that many of the EAP quickstarts will not work with the JWS Tomcat images.

**Comment by Arun129** [comment]
@rcernich 
@spolti yes am able to see those logs. am using "jboss-webserver30-tomcat8-openshift:1.2" template from openshift 3.0

I am using only custom sample archive files only for tomcat, which contains some sample logins.

this is the repository of the sample archive files which am trying to deploy in openshift tomcat. please find it below

https://github.com/Arun129/sample_repo

NOTE : I have successfully deployed this file in aws beasnstalk and I have got the desired output.

**Comment by josefkarasek** [comment]
That's not Java application in the first place ;-)
Tomcat is a servlet container for Java apps. What you want is a http server, such as Apache (httpd).

Use the PHP 5.6 , give your application some name and link the github url. In a while you'll get your html&css deployed on Openshift 3 ;-)

It took about 20 seconds http://php-app-jkarasek.44fs.preview.openshiftapps.com/

**Comment by Arun129** [comment]
Super !!!! It works. Thank you @josefkarasek

**Comment by Arun129** [comment]
But how AWS Elastic Beanstalk deploying the same file @josefkarasek
