### ISSUE TITLE
JBoss Data Virtualization template dependencies are broken

### ISSUE THREAD

**Issue by mechevarria** [jboss-openshift/application-templates#328]
https://github.com/jboss-openshift/application-templates/tree/master/datavirt

All of the templates reference datagrid client 1.0, which is not resolvable.  Version 1.1 is resolvable.

**Comment by spolti** [comment]
This issue will be tracked by https://issues.jboss.org/browse/CLOUD-1994.
Any questions please, do there.

I am closing this one.
