### ISSUE TITLE
Opeshift lab fails due to service account not created

### ISSUE THREAD

**Issue by nsevalia** [jboss-openshift/application-templates#419]
Going through RH OPEN training for "Application Development with Openshift" course. Topic Lab 2.4 : Java EE Application Deployment has steps (section 2.2)  to create service account & secret based  on the following command which creates secret but not service account "oc create -f application-templates/secrets/eap-app-secret.json".

This seem to lead failure in subsequent labs eg. Lab 4.
It appears that the eap-app-secret.json file is updated in the GIT repo to remove service account however as per training lab it should be created. Possible mismatch between repo & lab steps. Kindly correct either of this.

**Comment by spolti** [comment]
That's right, you can create the Service account by following this step: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/red_hat_jboss_enterprise_application_platform_for_openshift/installation_and_configuration#create_service_account_in_project

Thanks for report, I'll forward it to the training folks.

**Comment by nsevalia** [comment]
Is there any link for EAP 6 (and not 7)?



Thanks & Regards
Naishadh Sevalia

**Comment by spolti** [comment]
You can use the same doc, however, just pay attention on the topic 1.4. Comparison: JBoss EAP for OpenShift 6.4 and 7.

**Comment by spolti** [comment]
Alternatively you can use a different tag which contains the Service account:

https://github.com/jboss-openshift/application-templates/blob/ose-v1.4.7/secrets/eap-app-secret.json#L14

**Comment by wkulhanek** [comment]
@nsevalia Thank you for reporting this.
@spolti Thanks for the suggestion. I'm pinning the tag now in the instructions.
I just pushed the course content change - should be on the LMS later today or tomorrow.

**Comment by spolti** [comment]
@wkulhanek thanks.
I am closing this now, @nsevalia fell free to reopen if you have any other question.
