### ISSUE TITLE
Where is jboss-image-streams.json ?

### ISSUE THREAD

**Issue by paulosobreira** [jboss-openshift/application-templates#453]
I cant run :
oc create -n <myproject> -f jboss-image-streams.json

When I run : 

oc process -n <myproject> -f webserver/jws31-tomcat7-basic-s2i.json -p APPLICATION_NAME=<myapp> -p SOURCE_REPOSITORY_URL=<myGitUrl> -p SOURCE_REPOSITORY_REF=master -p CONTEXT_DIR=deployments | oc create -n <myproject> -f -

I got this when try to build :

The ImageStreamTag "jboss-webserver31-tomcat7-openshift:1.2" is invalid: from: Error resolving ImageStreamTag jboss-webserver31-tomcat7-openshift:1.2 in namespace openshift: unable to find latest tagged image

**Comment by jamesfalkner** [comment]
See https://github.com/jboss-openshift/application-templates/commit/5c3b6e7f2adf6f868b8b669464b3996c03842ae7 and https://issues.jboss.org/projects/CLOUD/issues/CLOUD-2419?filter=allissues the uber-imagestream file is gone, you need to install the individual imagestreams for each project/product.

**Comment by paulosobreira** [comment]
Thanks. I did this and works.
