### ISSUE TITLE
Need update "Yes/No" to true/false for template files

### ISSUE THREAD

**Issue by chunyunchen** [jboss-openshift/application-templates#49]
Met errors when processing relevant jboss template files, like below:

[chunchen@F17-CCY daily]$ oc process -f eap6-basic-sti.json 
error: unable to load "eap6-basic-sti.json": json: cannot unmarshal string into Go value of type bool

**Comment by knrc** [comment]
I suspect this is down to the version of the oc client being used, perhaps a recent change?  Which version are you using??

**Comment by josefkarasek** [comment]
Yes, I ran into this after upgrading to oc `v3.0.1.900-185-g2f7757a`.
After changing the values from type `string` to `bool` it works fine.

**Comment by jmtd** [comment]
This change has been made.
