### ISSUE TITLE
the template files under "eap/" sub-directory are outdated

### ISSUE THREAD

**Issue by chunyunchen** [jboss-openshift/application-templates#6]
1. Setup openshift v3 environment and login to the server
     oc login --server=$server-dns -u chun
      oc new-project chunp

   2. Process template with template file, eg:  eap/eap6-basic-sti.json
    oc process -f eap6-basic-sti.json
     Meet below messages:
error: unable to recognize "eap6-basic-sti.json": no object named "Template" is registered

****** the below template files are outdated ******
eap/eap-app-secret.json
eap/eap6-basic-sti.json 
eap/eap6-mongodb-sti.json
eap/eap6-mysql-sti.json
eap/eap6-postgresql-sti.json

Could you please help to have a check ?
Thanks!

**Comment by knrc** [comment]
On June 4th the following commit was made to the openshift code base removing support for the versions we are using within our templates, for now you can use these templates if you use the osc command from an earlier commit.

6d11b07a1d87fbdfeb579ecab6a763c1d464dbb4

**Comment by knrc** [comment]
BTW the latest tag of openshift, v0.5.4, works so use that.

**Comment by chunyunchen** [comment]
the issue is not reproduced now.
