### ISSUE TITLE
No tag for jboss-postgresql-92 in jws-tomcat7-postgresql-sti.json and jws-tomcat8-postgresql-sti.json

### ISSUE THREAD

**Issue by xiuwang** [jboss-openshift/application-templates#7]
No tag for jboss-postgresql-92 in jws-tomcat7-postgresql-sti.json and jws-tomcat8-postgresql-sti.json
                            "from": {
                                "kind": "ImageStreamTag",
                                "name": "jboss-postgresql-92"

**Comment by knrc** [comment]
https://issues.jboss.org/browse/CLOUD-137
