### ISSUE TITLE
Need rename MONGODB_USERNAME to MONGODB_USER in template files

### ISSUE THREAD

**Issue by chunyunchen** [jboss-openshift/application-templates#9]
According to https://github.com/openshift/mongodb#environment-variables , the env variable MONGODB_USERNAME should be renamed to MONGODB_USER

eg: https://github.com/jboss-openshift/application-templates/blob/master/eap/eap6-mongodb-sti.json

**Comment by fbricon** [comment]
Seems fixed in https://github.com/jboss-openshift/application-templates/commit/95d03dd2348d1151748471e9722c24e83e10fded

**Comment by jmtd** [comment]
Confirmed @fbricon , thanks
