### ISSUE TITLE
Image-stream tag could not be resolved

### ISSUE THREAD

**Issue by lorenzvth7** [jboss-openshift/application-templates#97]
The template uses image-streams. I'm using OpenShift Origin V3 (after an ansible install). It contains some templates and image-stream but not many.
So I had to install the image-streams manually from here:
https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json

I install the image-streams in my project. Than I create the template and use it.
But after I submit the template (in the web console) I get the following error when I want to build:
```An error occurred while starting the build.imageStream "jboss-eap64-openshift" not found```

I took a look to the image-stream:
``` 1.2 — Tag could not be resolved.```
A lot of image-stream were tagged by 1.2 in the template but the tags of the created image-stream are: 
```
1.2 — Tag could not be resolved.
1.1 — 1ac9fd Created 15 minutes ago
Pull spec: registry.access.redhat.com/jboss-amq-6/amq62-openshift:1.1
messagingamqjbossxpaas
1.1-2 — 1ac9fd Created 15 minutes ago
Pull spec: registry.access.redhat.com/jboss-amq-6/amq62-openshift:1.1-2
latest — 1ac9fd Created 15 minutes ago
Pull spec: registry.access.redhat.com/jboss-amq-6/amq62-openshift:latest 
```
It seems that tag 1.1-2 does not contain 1.2?
I manually tagged the image-stream to 1.2 but this did not solve the issue. I also tried to change the template to use 1.1 instead of 1.2 but also this did not work.

A direct deploy is not possible because that the application will use the application-name to search for the right image. It will not find it.

**Comment by knrc** [comment]
You are using a development stream, the 1.2 images are not yet released and are not available on registry.access.redhat.com.

Please use the version from the 1.1 tag if you are using v3.0,

https://github.com/jboss-openshift/application-templates/blob/ose-v1.1.0/jboss-image-streams.json

**Comment by lorenzvth7** [comment]
@knrc Okay, I have now installed the IS with the 1.1tag. But do I not need to change my template which is requesting for 1.2 image-streams?

**Comment by knrc** [comment]
@lorenzvth7 Yes, you will need to use the templates from the same tag

**Comment by rcernich** [comment]
By default, the templates expect the image streams to be installed in the "openshift" namespace.  If you're installing them in your own namespace, you'll need to change the value of the IMAGE_STREAM_NAMESPACE parameter to match the namespace where the image streams are installed.

**Comment by lorenzvth7** [comment]
@knrc @rcernich  Thanks, it solved my issue. I already had changed the namespace and it's all working now.

**Comment by lorenzvth7** [comment]
It's still building:

**Comment by lorenzvth7** [comment]
Its still building:
First error:
```Failed to pull image "secure": Error: image library/secure:latest not found```
Second error:
```
Couldn't create initial deployment: DeploymentConfig "secure" is invalid: triggers[0].imageChange.tag: invalid value 'latest', Details: no image recorded for passthrough/secure:latest
```
I don't understand why it's searching for image secure. (secure is the image name of my application)

**Comment by rcernich** [comment]
Sounds like you're using the default namespace, which I believe is "".  This means the repo name that gets used is "library".  I recommend creating a project, then doing your work within that project (namespace).

**Comment by rcernich** [comment]
As for the image "secure" that's the image that will be running, which contains your built source.  This is different from the base image.  This might help: https://docs.openshift.com/enterprise/3.0/dev_guide/builds.html

**Comment by lorenzvth7** [comment]
I am working a project (name passthrough). I also described it in the template. So it's all happening inside a project. even the image-streams are only in that project and they are used. And yes I thought they would use as base image an image-stream (passthrough/jboss-eap64-openshift:1.1) and than create a 'new' image: secure. But it keeps giving those errors after every build.

**Comment by lorenzvth7** [comment]
Now I see it's no issue about this, it's happening for every build at the moment! But it's offtopic so I will close this.
